### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by Emilef22** [daweizhangau/esphome_uni_trend_sound_meter#5]
Hello,
I already have the component install on another esp32 and it works great! Now i'm trying to install it on another esp32 ans i get this code:

INFO Reading configuration /config/esphome/store-toilette-soundmeter.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing store-toilette-soundmeter (board: esp32dev; framework: arduino; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
Library Manager: Installing Hash
INFO Installing Hash
Library Manager: Installing ESP8266WiFi
INFO Installing ESP8266WiFi
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 1.0
|-- FS @ 1.0
|-- Update @ 1.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 1.1.0
|-- ESPmDNS @ 1.0
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
|-- ArduinoJson @ 6.18.5
Compiling /data/store-toilette-soundmeter/.pioenvs/store-toilette-soundmeter/src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp.o
Compiling /data/store-toilette-soundmeter/.pioenvs/store-toilette-soundmeter/src/main.cpp.o
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp: In member function 'virtual void esphome::uni_trend_sound_meter::UnitTrendSoundMeter::gattc_event_handler(esp_gattc_cb_event_t, esp_gatt_if_t, esp_ble_gattc_cb_param_t*)':
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:73:63: error: 'class esphome::ble_client::BLEClient' has no member named 'gattc_if'
             esp_ble_gattc_register_for_notify(this->parent()->gattc_if, this->parent()->remote_bda, this->output_handle_);
                                                               ^
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:73:89: error: 'class esphome::ble_client::BLEClient' has no member named 'remote_bda'
             esp_ble_gattc_register_for_notify(this->parent()->gattc_if, this->parent()->remote_bda, this->output_handle_);
                                                                                         ^
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:83:52: error: 'class esphome::ble_client::BLEClient' has no member named 'conn_id'
       if (param->notify.conn_id != this->parent()->conn_id || param->notify.handle != this->output_handle_)
                                                    ^
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp: In member function 'virtual void esphome::uni_trend_sound_meter::UnitTrendSoundMeter::update()':
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:137:21: error: 'class esphome::ble_client::BLEClient' has no member named 'gattc_if'
     this->parent()->gattc_if, 
                     ^
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:138:21: error: 'class esphome::ble_client::BLEClient' has no member named 'conn_id'
     this->parent()->conn_id, 
                     ^
*** [/data/store-toilette-soundmeter/.pioenvs/store-toilette-soundmeter/src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp.o] Error 1
========================== [FAILED] Took 6.83 seconds ==========================

Can you please help me?
Thanks a lot!

**Comment by daweizhangau** [comment]
@Emilef22 ESP8266 doesn't support `esp32_ble_tracker`, you need to use a ESP32.

**Comment by Emilef22** [comment]
I can assure you that it is not on a 8266 and my Ble tracker works well.

**Comment by daweizhangau** [comment]
@Emilef22  I formatted your code, but just removing the `ap` section, which doesn't work for me. I cannot reproduce the issue you mentioned. 

```yaml
esphome:
  name: store-toilette-soundmeter

esp32:
  board: esp32dev
  framework:
    type: arduino
logger:

api:
  encryption:
    key: "4wL+Lp/nu3N9GLdCHrTrCsNR8eM6Gt0n8K3TKRomGZ8="

ota:
  password: "ba87bfb8788005a4374bb739a837bfb9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# ap:
#   ssid: "Store-Toilette-Soundmeter"
#   password: "AHqk7QPzi7Tv"

captive_portal:

external_components:
    source: github://daweizhangau/esphome_uni_trend_sound_meter@v1.0.0

esp32_ble_tracker:

uni_trend_sound_meter:
  name: "Sound Level"
  icon: 'mdi:microphone'
  unit_of_measurement: 'dBA'
  ble_client_id: sound_meter_ble_client
  update_interval: 1s
  
web_server:
  port: 80

ble_client:
  mac_address: E8:D0:3C:51:89:66
  id: sound_meter_ble_client

```


```text
Linking /data/store-toilette-soundmeter/.pioenvs/store-toilette-soundmeter/firmware.elf
RAM:   [==        ]  16.4% (used 53708 bytes from 327680 bytes)
Flash: [========= ]  88.5% (used 1624082 bytes from 1835008 bytes)
Building /data/store-toilette-soundmeter/.pioenvs/store-toilette-soundmeter/firmware.bin
esp32_create_combined_bin(["/data/store-toilette-soundmeter/.pioenvs/store-toilette-soundmeter/firmware.bin"], ["/data/store-toilette-soundmeter/.pioenvs/store-toilette-soundmeter/firmware.elf"])
Wrote 0x19c880 bytes to file /data/store-toilette-soundmeter/.pioenvs/store-toilette-soundmeter/firmware-factory.bin, ready to flash to offset 0x0
======================== [SUCCESS] Took 217.96 seconds ========================
INFO Successfully compiled program.
```
