### ISSUE TITLE
Error compiling the module in ESPHome 2024.2.2

### ISSUE THREAD

**Issue by adizanni** [daweizhangau/esphome_uni_trend_sound_meter#8]
Hello @daweizhangau , thanks for this custom component.

I've tried to compile your module using ESPHome 2024.2.2, I receive the following error:

```
Compiling .pioenvs/masterbedroom1-1/src/esphome/components/wifi/wifi_component.o
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp: In member function 'virtual void esphome::uni_trend_sound_meter::UnitTrendSoundMeter::gattc_event_handler(esp_gattc_cb_event_t, esp_gatt_if_t, esp_ble_gattc_cb_param_t*)':
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:73:63: error: 'class esphome::ble_client::BLEClient' has no member named 'gattc_if'; did you mean 'gattc_if_'?
             esp_ble_gattc_register_for_notify(this->parent()->gattc_if, this->parent()->remote_bda, this->output_handle_);
                                                               ^~~~~~~~
                                                               gattc_if_
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:73:89: error: 'class esphome::ble_client::BLEClient' has no member named 'remote_bda'; did you mean 'remote_bda_'?
             esp_ble_gattc_register_for_notify(this->parent()->gattc_if, this->parent()->remote_bda, this->output_handle_);
                                                                                         ^~~~~~~~~~
                                                                                         remote_bda_
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:83:52: error: 'class esphome::ble_client::BLEClient' has no member named 'conn_id'; did you mean 'conn_id_'?
       if (param->notify.conn_id != this->parent()->conn_id || param->notify.handle != this->output_handle_)
                                                    ^~~~~~~
                                                    conn_id_
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp: In member function 'virtual void esphome::uni_trend_sound_meter::UnitTrendSoundMeter::update()':
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:137:21: error: 'class esphome::ble_client::BLEClient' has no member named 'gattc_if'; did you mean 'gattc_if_'?
     this->parent()->gattc_if,
                     ^~~~~~~~
                     gattc_if_
src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.cpp:138:21: error: 'class esphome::ble_client::BLEClient' has no member named 'conn_id'; did you mean 'conn_id_'?
     this->parent()->conn_id,
                     ^~~~~~~
                     conn_id_
*** [.pioenvs/masterbedroom1-1/src/esphome/components/uni_trend_sound_meter/uni_trend_sound_meter.o] Error 1
```

The config is the following:

```yaml

external_components:
  - source: github://daweizhangau/esphome_uni_trend_sound_meter@v1.0.0 

ble_client:
  - mac_address: E8:D0:XX:XX:XX:XX
    id: ut_decibel_meter_terrace

uni_trend_sound_meter:
  name: "Terrace Sound Level"
  icon: 'mdi:microphone'
  unit_of_measurement: 'dBA'
  ble_client_id: ut_decibel_meter_terrace
  update_interval: 1s

```
